### ISSUE TITLE
Css problem at hover when the switch have not be clicked yet

### ISSUE THREAD

**Issue by loiclefloch** [Julusian/react-bootstrap-switch#12] opened 2016-04-03 20:10 UTC
Hello !

I have a switch put on a table row (tr). When hover the row, it's background-color is set to green. But it broke the color of bootstrap-switch if i haven't click on it since the page loading:

![screen shot 2016-04-03 at 22 01 53](https://cloud.githubusercontent.com/assets/3998603/14234636/ea88d0c0-f9e7-11e5-9db7-3e6809669008.png)

The error is due to the class `bootstrap-switch-animate` that is not set when the Switch component is instantiate, but set at the first click on the switch.

To solve this problem, i use the following tricks:

On the css:

``` css
.bootstrap-switch.bootstrap-switch-animate .bootstrap-switch-container {
  background-color: white;
}
```

And on my javascript react component:

``` javascript
componentDidMount() {
    $('.bootstrap-switch').addClass('bootstrap-switch-animate');
  }
```

The result:

![screen shot 2016-04-03 at 22 03 12](https://cloud.githubusercontent.com/assets/3998603/14234644/0f1cc63a-f9e8-11e5-9558-ad86ab6e99d2.png)

Can you solve this please ? Thanks in advance :)

**Comment by Julusian** [comment] 2016-04-05 23:02
Hi
I am unable to reproduce this issue myself, could you send me an example I can have a play with?

**Comment by loiclefloch** [comment] 2016-04-06 12:37
Hi,

You can find an example [here](https://github.com/loiclefloch/react-bootstrap-switch-issue-12-example).

This reproduce this issue but also the #10. Note that the #10 bug appear every time with size="mini" and sometimes with size="large".

**Comment by Julusian** [comment] 2016-04-06 19:44
I can see that you are using the css from the original switch. Your issue is one that has been fixed in the version in this repo.
The related changes were made in bbd9754b0cebb82aeb1724ca86c79529e4a7b9df

**Comment by loiclefloch** [comment] 2016-04-06 20:09
Thanks.
It's not really clear that we have to use this repositories css/js from 'dist' instead of the originals one, especially when you already used it and want to use your solution later :/

**Comment by Julusian** [comment] 2016-04-06 20:18
I have tried to make this as compatible as possible with the original css, but that is one issue that I don't think can be solved due to the behaviour of jsx.
I have also made a PR against the original repo with all the changes, and I shall add a note to the readme.

**Closed as completed by Julusian** 2016-04-06 20:18 UTC
