### ISSUE TITLE
Can't click the handle to toggle when mode is off

### ISSUE THREAD

**Issue by penguinpowernz** [Julusian/react-bootstrap-switch#7] opened 2016-01-19 07:20 UTC
Great library, but I have one tiny niggle.  When I use it the handle on the toggle switch cannot be clicked to action a toggle.  You have to drag the handle over to the other side in order to toggle it.  Clicking on the text toggles it as you would expect but clicking on the handle does nothing.

Have you seen this happen?  I couldn't see an option for dragging like in other toggle switch libraries I've used, and I went and checked the documentation on the bootstrap-switch site, but they have nothing on it either.  And all of their examples allow you to click the handle to toggle.  No mention of dragging.

Any ideas?

Edit: it actually only happens when the switch is off.  When it's on clicking the handle will toggle it.

**Comment by baronnoraz** [comment] 2016-01-20 20:52
I can confirm that this is happening with me.  It's very noticeable in our app as the toggle starts in the "off" state.   In the "off" position, user's can't click on the handle to toggle the state.  When it is in the "on" state, you can click the handle to toggle.

**Comment by penguinpowernz** [comment] 2016-01-21 05:17
@baronnoraz what version are you running?  I just saw I was running v3.3.4 which likely doesn't have the latest fix from #5  (v3.4.1).

**Comment by baronnoraz** [comment] 2016-01-21 14:36
I've tried v3.4.0 and v3.4.1.  I haven't tried to revert back to anything earlier.

**Comment by pdeva** [comment] 2016-01-23 09:46
+1
this is an annoying issue

**Comment by penguinpowernz** [comment] 2016-01-26 03:10
OK I tried 3.4.1 and it worked for me.  This was after I purged my `node_modules` folder.  @pdeva what version are you using?  @baronnoraz can you please try deleting your `node_modules` folder and try again (if you didn't already)?

**Comment by pdeva** [comment] 2016-01-26 07:54
I am using 3.4.1

**Comment by baronnoraz** [comment] 2016-01-26 14:21
Well, I'm embarrassed to say that I hadn't tried purging my `node_modules`.  Everything worked fine with 3.4.1 after I did though.  Thanks @penguinpowernz!

**Comment by Julusian** [comment] 2016-01-26 22:27
@pdeva are you able to try purging `node_modules`? I am unable to reproduce this in any of my projects.

**Comment by Julusian** [comment] 2016-02-08 17:27
I am closing this due to it appearing resolved. If it is not working for you, feel free to reopen or create a new issue.

**Closed as completed by Julusian** 2016-02-08 17:27 UTC
